# Generated by Django 3.1.2 on 2020-10-15 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor', models.CharField(max_length=200)),
                ('starting_datetime', models.DateTimeField()),
                ('home', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.PositiveSmallIntegerField()),
                ('stop', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('senior', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='VolunteeringRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('reward', models.PositiveSmallIntegerField(default=1)),
                ('senior', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, default=None, null=True)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Player'), (2, 'Admin')], default=None, null=True)),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('season', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='volunteers.season')),
                ('section', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='volunteers.section')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField()),
                ('phone', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MatchVolunteeringRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Sent'), (2, 'Accepted'), (3, 'Rejected'), (4, 'Cancelled')])),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.match')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.volunteeringrole')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.section')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.volunteer')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.season'),
        ),
        migrations.AddField(
            model_name='match',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.section'),
        ),
    ]
