# Generated by Django 3.1.2 on 2020-10-15 12:06
from django.db import migrations
from django.utils.translation import gettext as _


def create_seasons(apps, schema_editor):
    Season = apps.get_model('volunteers', 'Season')
    Season.objects.get_or_create(start=2020, stop=2021)


def create_sections(apps, schema_editor):
    section_names = (
        ('-12 F', False),
        ('-12 M', False),
        ('-14 F', False),
        ('-14 M', False),
        ('-16 F', False),
        ('-16 M', False),
        ('-19 F', False),
        ('-19 M', False),
        ('Senior F1', True),
        ('Senior F2', True),
        ('Senior M1', True),
        ('Senior M2', True),
    )
    Section = apps.get_model('volunteers', 'Section')
    for section in section_names:
        Section.objects.get_or_create(name=section[0], senior=section[1])


def create_volunteering_roles(apps, schema_editor):
    roles = (
        ### Senior
        {"name": _("Chronométreur table de marque"), "reward": 3, "senior": True},
        {"name": _("Secrétaire table de marque"), "reward": 3, "senior": True},
        {"name": _("Responsable de salle"), "reward": 3, "senior": True},
        {"name": _("Bénévole au bar"), "reward": 3, "senior": True},
        {"name": _("Arbitrage d’un match sénior"), "reward": 3, "senior": True},
        #### young
        {"name": _("Chronométreur table de marque"), "reward": 4, "senior": False},
        {"name": _("Secrétaire table de marque"), "reward": 4, "senior": False},
        {"name": _("Responsable de salle"), "reward": 4, "senior": False},
        {"name": _("Bénévole au bar"), "reward": 2, "senior": False},
        {"name": _("Arbitrage d’un match jeune"), "reward": 4, "senior": False},

    )

    VolunteeringRole = apps.get_model('volunteers', 'VolunteeringRole')
    for role in roles:
        VolunteeringRole.objects.get_or_create(**role)


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_seasons),
        migrations.RunPython(create_sections),
        migrations.RunPython(create_volunteering_roles),
    ]
